var items = [
  {
    id: 1,
    craftImage: require('../icons/profile.png'),
    craftName: 'omar',
    rating: 4,
    money: 10,
    period: '3 days',
  },
  {
    id: 2,
    craftImage: require('../icons/profile.png'),
    craftName: 'mohamed',
    rating: 2.2,
    money: 10,
    period: '3 days',
  },
  {
    id: 3,
    craftImage: require('../icons/profile.png'),
    craftName: 'bojy',
    rating: 3,
    money: 10,
    period: '3 days',
  },
  {
    id: 4,
    craftImage: require('../icons/profile.png'),
    craftName: 'moustafa',
    rating: 5,
    money: 10,
    period: '3 days',
  },
  {
    id: 5,
    craftImage: require('../icons/profile.png'),
    craftName: 'som3a',
    rating: 5,
    money: 10,
    period: '3 days',
  },
  {
    id: 6,
    craftImage: require('../icons/profile.png'),
    craftName: 'mazzika',
    rating: 5,
    money: 10,
    period: '3 days',
  },
  {
    id: 7,
    craftImage: require('../icons/profile.png'),
    craftName: 'aboshe',
    rating: 5,
    money: 10,
    period: '3 days',
  },
  {
    id: 8,
    craftImage: require('../icons/profile.png'),
    craftName: 'kadi',
    rating: 5,
    money: 10,
    period: '3 days',
  },
];
export default items;
